/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:6802bdd7-6c0e-40e7-a564-4b674ed88a39",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_4wQQJTHfU",
    "aws_user_pools_web_client_id": "edkud0m8d95gg2er33v4ubodq",
    "oauth": {},
    "aws_user_files_s3_bucket": "user-pdf-uploads121221-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
